// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SunflowerFund.API.Data;

namespace SunflowerFund.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190216182537_AddedUserEntity")]
    partial class AddedUserEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("SunflowerFund.API.models.Medical", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("areYouAHighRiskForhepatitisOrHiv");

                    b.Property<bool>("areYouAPlateletDonor");

                    b.Property<bool>("areYouARegularBloodDonor");

                    b.Property<bool>("areYouHealthy");

                    b.Property<bool>("areYouOrYourPartnerRiskOfSTI");

                    b.Property<bool>("areYouWillingToBeApproachedToBeAPlateletDonor");

                    b.Property<bool>("areYouWillingToBeAproachedToBeAPlatelet");

                    b.Property<bool>("dateOfLastPregnancy");

                    b.Property<bool>("doYouGetUpMorethanOnceAtNight");

                    b.Property<bool>("doesYourAnkleSwellEdnOfDay");

                    b.Property<bool>("doesYourFamilyAgreeForyouToDonate");

                    b.Property<bool>("haveYouEverBeenPregnant");

                    b.Property<bool>("haveYouEverBeenTestedForHiv");

                    b.Property<bool>("iAgreeToBeContactedBySANBSandWPBTSToDonatePlatelets");

                    b.Property<bool>("iAgreeToBiengContactedBySANBSAndWPBTSToDonatePlatelet");

                    b.Property<bool>("iConsentToMyPersonalInfoGiveToSANBS");

                    b.Property<bool>("iConsentToMyPersonalInformationBeingGivenSABSandWPBTS");

                    b.Property<bool>("ifSoNumberOfPregnancies");

                    b.Property<int>("whatsYourHeight");

                    b.Property<int>("whatsYourWeight");

                    b.HasKey("id");

                    b.ToTable("MedicalsScreening");
                });

            modelBuilder.Entity("SunflowerFund.API.models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
